#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/markw

PRODUCT_COPY_FILES += \
    vendor/xiaomi/markw/proprietary/etc/permissions/privapp-permissions-qti.xml:$(TARGET_COPY_OUT_ETC)/permissions/privapp-permissions-qti.xml \
    vendor/xiaomi/markw/proprietary/etc/sysconfig/qti_whitelist.xml:$(TARGET_COPY_OUT_ETC)/sysconfig/qti_whitelist.xml \
    vendor/xiaomi/markw/proprietary/product/etc/permissions/telephony_product_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/telephony_product_privapp-permissions-qti.xml \
    vendor/xiaomi/markw/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/xiaomi/markw/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/xiaomi/markw/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/xiaomi/markw/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/xiaomi/markw/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/xiaomi/markw/proprietary/system_ext/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/xiaomi/markw/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/xiaomi/markw/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/xiaomi/markw/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/xiaomi/markw/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/xiaomi/markw/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/xiaomi/markw/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/xiaomi/markw/proprietary/vendor/etc/apdr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/apdr.conf \
    vendor/xiaomi/markw/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_camera.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_chromatix.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/camera/ofilm_s5k3l8_f3l8yam_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ofilm_s5k3l8_f3l8yam_chromatix.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/camera/ov5670_f5670bq_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov5670_f5670bq_chromatix.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/camera/qtech_ov5670_f5670bq_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/qtech_ov5670_f5670bq_chromatix.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/camera/qtech_s5k3l8_f3l8yam_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/qtech_s5k3l8_f3l8yam_chromatix.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/camera/s5k3l8_f3l8yam_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3l8_f3l8yam_chromatix.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/camera/s5k5e8_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k5e8_chromatix.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/camera/sunny_s5k3l8_f3l8yam_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sunny_s5k3l8_f3l8yam_chromatix.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/android.hardware.drm-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.widevine.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/ims_rtp_daemon_legacy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon_legacy.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/init-qcril-data.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init-qcril-data.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@2.0-service.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/vendor.qti.hardware.perf@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf@2.2-service.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/xiaomi/markw/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/xiaomi/markw/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/xiaomi/markw/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/xiaomi/markw/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/qdcm_calib_data_nt35596_1080p_video_EBBG.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt35596_1080p_video_EBBG.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/qdcm_calib_data_r63350_1080p_video_Tianma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_r63350_1080p_video_Tianma.xml \
    vendor/xiaomi/markw/proprietary/vendor/etc/qmi_fw.conf:$(TARGET_COPY_OUT_VENDOR)/etc/qmi_fw.conf \
    vendor/xiaomi/markw/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/xiaomi/markw/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/xiaomi/markw/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    vendor/xiaomi/markw/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/xiaomi/markw/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/xiaomi/markw/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/xiaomi/markw/proprietary/vendor/etc/xtwifi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/xtwifi.conf \
    vendor/xiaomi/markw/proprietary/vendor/firmware/a506_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.b00 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/a506_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.b01 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/a506_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.b02 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/a506_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.mdt \
    vendor/xiaomi/markw/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/xiaomi/markw/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/xiaomi/markw/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/xiaomi/markw/proprietary/vendor/firmware/venus.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b00 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/venus.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b01 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/venus.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b02 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/venus.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b03 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/venus.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b04 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/venus.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mdt \
    vendor/xiaomi/markw/proprietary/vendor/firmware/wcnss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wcnss.b00 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/wcnss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wcnss.b01 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/wcnss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wcnss.b02 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/wcnss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wcnss.b04 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/wcnss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wcnss.b06 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/wcnss.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/wcnss.b09 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/wcnss.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/wcnss.b10 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/wcnss.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/wcnss.b11 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/wcnss.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/wcnss.b12 \
    vendor/xiaomi/markw/proprietary/vendor/firmware/wcnss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wcnss.mdt \
    vendor/xiaomi/markw/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/xiaomi/markw/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/xiaomi/markw/proprietary/vendor/radio/qcril_database/upgrade/10_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/10_version_update_ecc_table.sql \
    vendor/xiaomi/markw/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/xiaomi/markw/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/xiaomi/markw/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/xiaomi/markw/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/xiaomi/markw/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    vendor/xiaomi/markw/proprietary/vendor/radio/qcril_database/upgrade/6_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    vendor/xiaomi/markw/proprietary/vendor/radio/qcril_database/upgrade/7_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql \
    vendor/xiaomi/markw/proprietary/vendor/radio/qcril_database/upgrade/8_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/8_version_update_ecc_table.sql \
    vendor/xiaomi/markw/proprietary/vendor/radio/qcril_database/upgrade/9_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/9_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    vulkan.adreno \
    libC2D2 \
    libCB \
    libOpenCL \
    libQSEEComAPI \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libc2d30_bltlib \
    libdapparamstorage \
    libdiag \
    libdsutils \
    libfastcvadsp_stub \
    libfastcvopt \
    libgpudataproducer \
    libgsl \
    libhdr_tm \
    libidl \
    libllvm-glnext \
    libmdmdetect \
    libmdsprpc \
    libmm-hdcpmgr \
    libpdmapper \
    libqcci_legacy \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libscalar \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsensor1 \
    libsensor_reg \
    libtinyxml2_1 \
    sensors.ssc \
    vendor.dolby.hardware.dms@2.0 \
    vendor.qti.hardware.dsp@1.0 \
    libOmxAacDec \
    libOmxAmrDec \
    libOmxAmrwbplusDec \
    libOmxApeDec \
    libOmxDsdDec \
    libOmxEvrcDec \
    libOmxG711Dec \
    libOmxQcelp13Dec \
    libOmxWmaDec \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libactuator_bu64244gwz \
    libactuator_bu64291gwz \
    libactuator_dw9763 \
    libactuator_pseudo \
    libadiertac \
    libadm \
    libadpcmdec \
    libaudcal \
    libaudioalsa \
    libaudioparsers \
    libcapiv2svacnn \
    libcapiv2vop \
    libchromaflash \
    libchromatix_csidtg_common \
    libchromatix_csidtg_cpp_preview \
    libchromatix_csidtg_postproc \
    libchromatix_csidtg_preview \
    libchromatix_csidtg_zsl_preview \
    libchromatix_ofilm_s5k3l8_f3l8yam_common \
    libchromatix_ofilm_s5k3l8_f3l8yam_cpp_hfr_120 \
    libchromatix_ofilm_s5k3l8_f3l8yam_cpp_hfr_60 \
    libchromatix_ofilm_s5k3l8_f3l8yam_cpp_hfr_90 \
    libchromatix_ofilm_s5k3l8_f3l8yam_cpp_liveshot \
    libchromatix_ofilm_s5k3l8_f3l8yam_cpp_preview \
    libchromatix_ofilm_s5k3l8_f3l8yam_cpp_snapshot \
    libchromatix_ofilm_s5k3l8_f3l8yam_cpp_video \
    libchromatix_ofilm_s5k3l8_f3l8yam_default_preview_dw9763 \
    libchromatix_ofilm_s5k3l8_f3l8yam_default_video \
    libchromatix_ofilm_s5k3l8_f3l8yam_default_video_dw9763 \
    libchromatix_ofilm_s5k3l8_f3l8yam_hfr_120 \
    libchromatix_ofilm_s5k3l8_f3l8yam_hfr_120_dw9763 \
    libchromatix_ofilm_s5k3l8_f3l8yam_hfr_60 \
    libchromatix_ofilm_s5k3l8_f3l8yam_hfr_60_dw9763 \
    libchromatix_ofilm_s5k3l8_f3l8yam_hfr_90 \
    libchromatix_ofilm_s5k3l8_f3l8yam_hfr_90_dw9763 \
    libchromatix_ofilm_s5k3l8_f3l8yam_liveshot \
    libchromatix_ofilm_s5k3l8_f3l8yam_postproc \
    libchromatix_ofilm_s5k3l8_f3l8yam_preview \
    libchromatix_ofilm_s5k3l8_f3l8yam_snapshot \
    libchromatix_ofilm_s5k3l8_f3l8yam_zsl_preview_dw9763 \
    libchromatix_ofilm_s5k3l8_f3l8yam_zsl_video_dw9763 \
    libchromatix_ov5670_f5670bq_a3_default_preview \
    libchromatix_ov5670_f5670bq_a3_default_video \
    libchromatix_ov5670_f5670bq_a3_hfr_120 \
    libchromatix_ov5670_f5670bq_a3_hfr_60 \
    libchromatix_ov5670_f5670bq_a3_hfr_90 \
    libchromatix_ov5670_f5670bq_common \
    libchromatix_ov5670_f5670bq_cpp_ds_chromatix \
    libchromatix_ov5670_f5670bq_cpp_hfr_120 \
    libchromatix_ov5670_f5670bq_cpp_hfr_60 \
    libchromatix_ov5670_f5670bq_cpp_hfr_90 \
    libchromatix_ov5670_f5670bq_cpp_liveshot \
    libchromatix_ov5670_f5670bq_cpp_preview \
    libchromatix_ov5670_f5670bq_cpp_snapshot \
    libchromatix_ov5670_f5670bq_cpp_us_chromatix \
    libchromatix_ov5670_f5670bq_cpp_video \
    libchromatix_ov5670_f5670bq_cpp_video_full \
    libchromatix_ov5670_f5670bq_default_video \
    libchromatix_ov5670_f5670bq_hfr_120 \
    libchromatix_ov5670_f5670bq_hfr_60 \
    libchromatix_ov5670_f5670bq_hfr_90 \
    libchromatix_ov5670_f5670bq_liveshot \
    libchromatix_ov5670_f5670bq_postproc \
    libchromatix_ov5670_f5670bq_preview \
    libchromatix_ov5670_f5670bq_snapshot \
    libchromatix_ov5670_f5670bq_video_full \
    libchromatix_ov5670_f5670bq_zsl_preview \
    libchromatix_ov5670_f5670bq_zsl_video \
    libchromatix_qtech_ov5670_f5670bq_a3_default_preview \
    libchromatix_qtech_ov5670_f5670bq_a3_default_video \
    libchromatix_qtech_ov5670_f5670bq_a3_hfr_120 \
    libchromatix_qtech_ov5670_f5670bq_a3_hfr_60 \
    libchromatix_qtech_ov5670_f5670bq_a3_hfr_90 \
    libchromatix_qtech_ov5670_f5670bq_common \
    libchromatix_qtech_ov5670_f5670bq_cpp_ds_chromatix \
    libchromatix_qtech_ov5670_f5670bq_cpp_hfr_120 \
    libchromatix_qtech_ov5670_f5670bq_cpp_hfr_60 \
    libchromatix_qtech_ov5670_f5670bq_cpp_hfr_90 \
    libchromatix_qtech_ov5670_f5670bq_cpp_liveshot \
    libchromatix_qtech_ov5670_f5670bq_cpp_preview \
    libchromatix_qtech_ov5670_f5670bq_cpp_snapshot \
    libchromatix_qtech_ov5670_f5670bq_cpp_us_chromatix \
    libchromatix_qtech_ov5670_f5670bq_cpp_video \
    libchromatix_qtech_ov5670_f5670bq_cpp_video_full \
    libchromatix_qtech_ov5670_f5670bq_default_video \
    libchromatix_qtech_ov5670_f5670bq_hfr_120 \
    libchromatix_qtech_ov5670_f5670bq_hfr_60 \
    libchromatix_qtech_ov5670_f5670bq_hfr_90 \
    libchromatix_qtech_ov5670_f5670bq_liveshot \
    libchromatix_qtech_ov5670_f5670bq_postproc \
    libchromatix_qtech_ov5670_f5670bq_preview \
    libchromatix_qtech_ov5670_f5670bq_snapshot \
    libchromatix_qtech_ov5670_f5670bq_video_full \
    libchromatix_qtech_ov5670_f5670bq_zsl_preview \
    libchromatix_qtech_ov5670_f5670bq_zsl_video \
    libchromatix_qtech_s5k3l8_f3l8yam_common \
    libchromatix_qtech_s5k3l8_f3l8yam_cpp_hfr_120 \
    libchromatix_qtech_s5k3l8_f3l8yam_cpp_hfr_60 \
    libchromatix_qtech_s5k3l8_f3l8yam_cpp_hfr_90 \
    libchromatix_qtech_s5k3l8_f3l8yam_cpp_liveshot \
    libchromatix_qtech_s5k3l8_f3l8yam_cpp_preview \
    libchromatix_qtech_s5k3l8_f3l8yam_cpp_snapshot \
    libchromatix_qtech_s5k3l8_f3l8yam_cpp_video \
    libchromatix_qtech_s5k3l8_f3l8yam_default_preview_dw9763 \
    libchromatix_qtech_s5k3l8_f3l8yam_default_video \
    libchromatix_qtech_s5k3l8_f3l8yam_default_video_dw9763 \
    libchromatix_qtech_s5k3l8_f3l8yam_hfr_120 \
    libchromatix_qtech_s5k3l8_f3l8yam_hfr_120_dw9763 \
    libchromatix_qtech_s5k3l8_f3l8yam_hfr_60 \
    libchromatix_qtech_s5k3l8_f3l8yam_hfr_60_dw9763 \
    libchromatix_qtech_s5k3l8_f3l8yam_hfr_90 \
    libchromatix_qtech_s5k3l8_f3l8yam_hfr_90_dw9763 \
    libchromatix_qtech_s5k3l8_f3l8yam_liveshot \
    libchromatix_qtech_s5k3l8_f3l8yam_postproc \
    libchromatix_qtech_s5k3l8_f3l8yam_preview \
    libchromatix_qtech_s5k3l8_f3l8yam_snapshot \
    libchromatix_qtech_s5k3l8_f3l8yam_zsl_preview_dw9763 \
    libchromatix_qtech_s5k3l8_f3l8yam_zsl_video_dw9763 \
    libchromatix_s5k3l8_f3l8yam_common \
    libchromatix_s5k3l8_f3l8yam_cpp_hfr_120 \
    libchromatix_s5k3l8_f3l8yam_cpp_hfr_60 \
    libchromatix_s5k3l8_f3l8yam_cpp_hfr_90 \
    libchromatix_s5k3l8_f3l8yam_cpp_liveshot \
    libchromatix_s5k3l8_f3l8yam_cpp_preview \
    libchromatix_s5k3l8_f3l8yam_cpp_snapshot \
    libchromatix_s5k3l8_f3l8yam_cpp_video \
    libchromatix_s5k3l8_f3l8yam_default_preview_dw9763 \
    libchromatix_s5k3l8_f3l8yam_default_video \
    libchromatix_s5k3l8_f3l8yam_default_video_dw9763 \
    libchromatix_s5k3l8_f3l8yam_hfr_120 \
    libchromatix_s5k3l8_f3l8yam_hfr_120_dw9763 \
    libchromatix_s5k3l8_f3l8yam_hfr_60 \
    libchromatix_s5k3l8_f3l8yam_hfr_60_dw9763 \
    libchromatix_s5k3l8_f3l8yam_hfr_90 \
    libchromatix_s5k3l8_f3l8yam_hfr_90_dw9763 \
    libchromatix_s5k3l8_f3l8yam_liveshot \
    libchromatix_s5k3l8_f3l8yam_postproc \
    libchromatix_s5k3l8_f3l8yam_preview \
    libchromatix_s5k3l8_f3l8yam_snapshot \
    libchromatix_s5k3l8_f3l8yam_zsl_preview_dw9763 \
    libchromatix_s5k3l8_f3l8yam_zsl_video_dw9763 \
    libchromatix_s5k5e8_a3_default_preview \
    libchromatix_s5k5e8_a3_default_video \
    libchromatix_s5k5e8_a3_hfr_120 \
    libchromatix_s5k5e8_a3_hfr_60 \
    libchromatix_s5k5e8_a3_hfr_90 \
    libchromatix_s5k5e8_common \
    libchromatix_s5k5e8_cpp_ds_chromatix \
    libchromatix_s5k5e8_cpp_hfr_120 \
    libchromatix_s5k5e8_cpp_hfr_60 \
    libchromatix_s5k5e8_cpp_hfr_90 \
    libchromatix_s5k5e8_cpp_liveshot \
    libchromatix_s5k5e8_cpp_preview \
    libchromatix_s5k5e8_cpp_snapshot \
    libchromatix_s5k5e8_cpp_us_chromatix \
    libchromatix_s5k5e8_cpp_video \
    libchromatix_s5k5e8_default_video \
    libchromatix_s5k5e8_hfr_120 \
    libchromatix_s5k5e8_hfr_60 \
    libchromatix_s5k5e8_hfr_90 \
    libchromatix_s5k5e8_liveshot \
    libchromatix_s5k5e8_postproc \
    libchromatix_s5k5e8_preview \
    libchromatix_s5k5e8_snapshot \
    libchromatix_s5k5e8_zsl_preview \
    libchromatix_s5k5e8_zsl_video \
    libchromatix_sunny_s5k3l8_f3l8yam_common \
    libchromatix_sunny_s5k3l8_f3l8yam_cpp_hfr_120 \
    libchromatix_sunny_s5k3l8_f3l8yam_cpp_hfr_60 \
    libchromatix_sunny_s5k3l8_f3l8yam_cpp_hfr_90 \
    libchromatix_sunny_s5k3l8_f3l8yam_cpp_liveshot \
    libchromatix_sunny_s5k3l8_f3l8yam_cpp_preview \
    libchromatix_sunny_s5k3l8_f3l8yam_cpp_snapshot \
    libchromatix_sunny_s5k3l8_f3l8yam_cpp_video \
    libchromatix_sunny_s5k3l8_f3l8yam_default_preview_dw9763 \
    libchromatix_sunny_s5k3l8_f3l8yam_default_video \
    libchromatix_sunny_s5k3l8_f3l8yam_default_video_dw9763 \
    libchromatix_sunny_s5k3l8_f3l8yam_hfr_120 \
    libchromatix_sunny_s5k3l8_f3l8yam_hfr_120_dw9763 \
    libchromatix_sunny_s5k3l8_f3l8yam_hfr_60 \
    libchromatix_sunny_s5k3l8_f3l8yam_hfr_60_dw9763 \
    libchromatix_sunny_s5k3l8_f3l8yam_hfr_90 \
    libchromatix_sunny_s5k3l8_f3l8yam_hfr_90_dw9763 \
    libchromatix_sunny_s5k3l8_f3l8yam_liveshot \
    libchromatix_sunny_s5k3l8_f3l8yam_postproc \
    libchromatix_sunny_s5k3l8_f3l8yam_preview \
    libchromatix_sunny_s5k3l8_f3l8yam_snapshot \
    libchromatix_sunny_s5k3l8_f3l8yam_zsl_preview_dw9763 \
    libchromatix_sunny_s5k3l8_f3l8yam_zsl_video_dw9763 \
    libdeccfg \
    libdrc \
    libflash_pmic \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libllvd_smore \
    libllvd_sw_tnr \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_dcrf \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_modules \
    libmmcamera_chromaflash_lib \
    libmmcamera_csidtg \
    libmmcamera_dbg \
    libmmcamera_dcrf_lib \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_imglib \
    libmmcamera_isp_abf40 \
    libmmcamera_isp_bcc40 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats44 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc40 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct40 \
    libmmcamera_isp_color_xform_encoder40 \
    libmmcamera_isp_color_xform_viewfinder40 \
    libmmcamera_isp_cs_stats44 \
    libmmcamera_isp_demosaic40 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder40 \
    libmmcamera_isp_fovcrop_viewfinder40 \
    libmmcamera_isp_gamma40 \
    libmmcamera_isp_ihist_stats44 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff40 \
    libmmcamera_isp_rs_stats44 \
    libmmcamera_isp_scaler_encoder44 \
    libmmcamera_isp_scaler_viewfinder44 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_template \
    libmmcamera_isp_wb40 \
    libmmcamera_llvd \
    libmmcamera_optizoom_lib \
    libmmcamera_ov5670 \
    libmmcamera_ov5670_eeprom \
    libmmcamera_ov5670_sunny \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k3l8 \
    libmmcamera_s5k3l8_eeprom \
    libmmcamera_s5k3l8_mono \
    libmmcamera_s5k5e8 \
    libmmcamera_s5k5e8_eeprom \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_trueportrait_lib \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera_ubifocus_lib \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    liboptizoom \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libqtigef \
    libremosaic_daemon \
    libseemore \
    libsmwrapper \
    libstagefright_soft_ac4dec \
    libstagefright_soft_ddpdec \
    libtrueportrait \
    libts_detected_face_hal \
    libts_face_beautify_hal \
    libubifocus \
    libvqzip \
    libwvaidl \
    libspatialaudio \
    libswdap \
    libswgamedap \
    libswvqe \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    com.qualcomm.qti.uceservice@2.3 \
    deviceInfoServiceModule \
    android.hardware.bluetooth@1.0-impl-qti \
    com.dsi.ant@1.0-impl \
    fingerprint.fpc \
    fingerprint.goodix \
    gatekeeper.msm8953 \
    gxfingerprint.default \
    keystore.msm8953 \
    vendor.qti.gnss@4.0-impl \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    lib-imsSDP \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsvtcore \
    lib-imsxml \
    lib-rcsconfig \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libGPreqcancel \
    libGPreqcancel_svc \
    libSecureUILib \
    libStDrvInt \
    libbt-hidlclient \
    libbtnv \
    libcacertclient \
    libcdfw \
    libcdfw_remote_api \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcom_fingerprints_service \
    libconfigdb \
    libcpion \
    libdataitems \
    libdlbdsservice \
    libdpmqmihal \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libfp_client \
    libfpnav \
    libfpservice \
    libgdtap \
    libhdcpsrm \
    libizat_client_api \
    libizat_core \
    liblbs_core \
    libloc_api_v02 \
    libloc_socket \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libnetmgr \
    libnetmgr_common \
    libnlnetmgr \
    libperfconfig \
    libperfgluelayer \
    libperfioctl \
    libperipheral_client \
    libqcc_file_agent \
    libqcmaputils \
    libqcrilFramework \
    libqcrildatactl \
    libqisl \
    libqrtr \
    libqsocket \
    libqti-perfd-client-vendor \
    libqti-perfd \
    libqti-util-vendor \
    libqti-util \
    librcc \
    libril-qc-hal-qmi \
    libril-qc-logger \
    librilqmiservices \
    librpmb \
    libsecureui \
    libsecureui_svcsock \
    libsettings \
    libsoc_helper \
    libssd \
    libsystem_health_mon \
    libthermalclient \
    libthermalfeature \
    libtime_genoff \
    libwms \
    libwqe \
    libxml \
    libxtadapter \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    vendor.dolby.hardware.dms@2.0-impl \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.gnss@4.0-service \
    vendor.qti.gnss@4.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.ims@1.7 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.factory@1.1 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.imsrtpservice@3.0_vendor \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    vendor.qti.memory.pasrmanager@1.0 \
    vendor.qti.memory.pasrmanager@1.1 \
    libadsp_fd_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    com.qualcomm.qti.ant@1.0 \
    com.qualcomm.qti.dpm.api@1.0 \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.api@1.1 \
    com.quicinc.cne.constants@1.0 \
    com.quicinc.cne.constants@2.0 \
    com.quicinc.cne.constants@2.1 \
    lib-imscamera \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libimscamera_jni \
    libimsmedia_jni \
    libmwqemiptablemgr \
    vendor.qti.diaghal@1.0 \
    vendor.qti.imsrtpservice@3.0 \
    CneApp \
    IWlanService \
    TimeService \
    PowerOffAlarm \
    QtiTelephonyService \
    ims \
    qcrilmsgtunnel \
    com.qti.dpmframework \
    dpmapi \
    qcrilhook \
    manifest_android.hardware.drm-service.widevine.xml \
    manifest_vendor.dolby.hardware.dms.xml \
    vendor.qti.gnss@4.0-service.xml \
    adpl \
    adsprpcd \
    cnd \
    dspservice \
    gx_fpd \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm-service.widevine \
    qcrild \
    vendor.dolby.hardware.dms@2.0-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.perf@2.2-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    loc_launcher \
    lowi-server \
    msm_irqbalance \
    netmgrd \
    pm-proxy \
    pm-service \
    port-bridge \
    power_off_alarm \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    rmt_storage \
    sensors.qti \
    tftp_server \
    thermal-engine \
    time_daemon \
    xtra-daemon

PRODUCT_PACKAGES += \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so
